name: Apply Migrations

on:
  push:
    branches: [ main ]
jobs:
  apply_migrations:
    runs-on: ubuntu-latest
    env:
      supabase_db_url: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Apply Migrations
        run: supabase db push --db-url "$supabase_db_url"
